detect_model:
  path_yolo: './src/weights/detect/yolov5.pt'
  path_onet: './src/weights/detect/onet.pth'
  path_pnet: './src/weights/detect/pnet.pth'
  path_frcnn: './src/weights/detect/fasterrcnn.pth'
ocr_model:
  path_easy_custom: './src/weights/ocr/easyocr_custom.pth'
  path_lpr: './src/weights/ocr/lprnet.pth'
transform_model:
  path_stn: './src/weights/transform/stn.pth'
