detect_model:
  path_yolo: './src/weights/detect/yolov5_best.pt'
  path_onet: './src/weights/detect/onet.pth'
  path_pnet: './src/weights/detect/pnet.pth'
  path_frcnn: './src/weights/detect/FasterRCNN_v1_last.pth'
ocr_model:
  path_easy_custom: './src/weights/ocr/EasyOCR_custom.yaml.pth'
  path_lpr: './src/weights/ocr/lprnet.pth'
transform_model:
  path_stn: './src/weights/transform/stn.pth'
